# Generated by Django 4.1.4 on 2022-12-09 17:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0002_alter_proyecto_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='fecha',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 9, 12, 2, 14, 372214)),
        ),
    ]
