# Generated by Django 4.1.4 on 2022-12-12 03:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0003_proyecto_fecha_proyecto_fecha_creacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ipvisitante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipvisita', models.CharField(max_length=100)),
                ('fecha_creacion', models.DateTimeField(default=datetime.datetime(2022, 12, 11, 22, 44, 39, 451368))),
            ],
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 11, 22, 44, 39, 448382)),
        ),
    ]
